version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=spotify
    ports:
      - '5432:5432'
  elasticsearch:
    image: elasticsearch:7.17.9
    restart: always
    environment:
      - "discovery.type=single-node"
    ports:
      - '9200:9200'
